name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'  # Specify the OpenJDK distribution

      - name: Install Kotlin
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        if: contains(github.event.head_commit.message, '[release]')
        run: ./gradlew publish

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}